# -*- coding: utf-8 -*-
"""AWS Lambda Trigger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDEHW8H-U6yCMiJX-d8DKIVyychQrthe
"""

import os
import boto3

def lambda_handler(event, context):
    region = os.environ["REGION_NAME"]
    cluster_id = os.environ["REDSHIFT_CLUSTER_ID"]
    database = os.environ["REDSHIFT_DATABASE"]
    db_user = os.environ["REDSHIFT_USER"]
    role_arn = os.environ["REDSHIFT_ROLE_ARN"]

    redshift = boto3.client("redshift-data", region_name=region)

    for record in event["Records"]:
        bucket = record["s3"]["bucket"]["name"]
        key = record["s3"]["object"]["key"]
        s3_path = f"s3://{bucket}/{key}"
        print(f"📁 New file detected: {s3_path}")

        # Identify target table
        if "cleaned_df_data.csv" in key:
            table_name = "public.news_events_data"
            expected_columns = 12
        elif "cleaned_df_included.csv" in key:
            table_name = "public.news_events_included"
            expected_columns = 9
        else:
            print(f"⚠️ File {key} not recognized. Skipping.")
            continue

        print(f"🚀 Starting COPY for {table_name} ({expected_columns} columns)...")

        # Optional cleanup before load
        truncate_sql = f"TRUNCATE TABLE {table_name};"
        redshift.execute_statement(
            ClusterIdentifier=cluster_id,
            Database=database,
            DbUser=db_user,
            Sql=truncate_sql
        )
        print(f"🧹 {table_name} truncated before load.")

        # COPY data
        copy_sql = f"""
        COPY {table_name}
        FROM '{s3_path}'
        IAM_ROLE '{role_arn}'
        REGION '{region}'
        FORMAT AS CSV
        IGNOREHEADER 1
        TRUNCATECOLUMNS
        ACCEPTINVCHARS
        BLANKSASNULL
        EMPTYASNULL;
        """
        response = redshift.execute_statement(
            ClusterIdentifier=cluster_id,
            Database=database,
            DbUser=db_user,
            Sql=copy_sql
        )
        print(f"✅ COPY started for {table_name}. Query ID: {response['Id']}")

    print("🎉 All recognized files processed successfully.")
    return {"status": "success"}